version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: messaging_app  # Add this line to match your build command
    command: gunicorn --bind 0.0.0.0:8000 your_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=robustapp
      - POSTGRES_USER=robustuser
      - POSTGRES_PASSWORD=robustpass

  redis:
    image: redis:7-alpine

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A your_project worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
